In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\customer chrun\data\raw\messy_customer_churn_100k.csv")

In [4]:
df.shape

(102000, 11)

In [5]:
df.sample(10)

,customer_id,gender,age,tenure,monthly_charges,total_charges,contract_type,payment_method,internet_service,churn,signup_date
4093,77450.0,Male,34,57.0,133.33,9376.70,Two year,Net Banking,NaN,N,NaN
92093,29785.0,NaN,24,43.0,117.17,9938.54,NaN,Debit Card,NaN,No,2022-07-21
36665,23405.0,NaN,21,59.0,71.36,2793.49,Two year,UPI,NaN,Yes,2021-03-25
86038,56713.0,NaN,43,47.0,122.30,8493.87,Two year,Credit Card,DSL,N,2020/04/30
93102,30161.0,Female,43,23.0,40.37,109.00,NaN,Debit Card,NaN,N,12/12/2022
98575,61582.0,F,43,37.0,56.18,5642.73,NaN,NaN,DSL,No,2023-01-03
58589,94256.0,F,69,48.0,40.34,7461.08,month-to-month,UPI,DSL,N,2023-06-29
57673,54217.0,NaN,30,12.0,104.17,8484.37,Monthly,UPI,DSL,Yes,2021/01/06
14599,20619.0,F,33,50.0,19.59,9375.72,NaN,NaN,NaN,Yes,06/04/2023
80532,30157.0,Male,52,15.0,88.66,6735.92,month-to-month,Debit Card,NaN,No,01-25-2021

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102000 entries, 0 to 101999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       99885 non-null  float64
 1   gender            79840 non-null  str
 2   age               98050 non-null  str
 3   tenure            98271 non-null  float64
 4   monthly_charges   99880 non-null  float64
 5   total_charges     99886 non-null  float64
 6   contract_type     79891 non-null  str
 7   payment_method    79828 non-null  str
 8   internet_service  49842 non-null  str
 9   churn             99882 non-null  str
 10  signup_date       99879 non-null  str
dtypes: float64(4), str(7)
memory usage: 8.6 MB

In [7]:
df.describe()

        customer_id        tenure  monthly_charges  total_charges
count  99885.000000  98271.000000     99880.000000   99886.000000
mean   54942.840276     30.004610        79.992573    5043.966770
std    26078.792831     17.047907        40.398797    2855.743225
min    10001.000000      1.000000        10.000000     100.210000
25%    32195.000000     15.000000        44.920000    2573.880000
50%    55024.000000     30.000000        80.000000    5055.460000
75%    77506.000000     45.000000       115.040000    7508.785000
max    99998.000000     59.000000       150.000000    9999.870000

In [8]:
df.isnull().sum()

customer_id          2115
gender              22160
age                  3950
tenure               3729
monthly_charges      2120
total_charges        2114
contract_type       22109
payment_method      22172
internet_service    52158
churn                2118
signup_date          2121
dtype: int64

In [9]:
df[df['customer_id'].isnull()]

,customer_id,gender,age,tenure,monthly_charges,total_charges,contract_type,payment_method,internet_service,churn,signup_date
13,NaN,M,33,13.0,103.91,8542.00,Monthly,NaN,DSL,Yes,04-30-2022
26,NaN,M,NaN,NaN,109.34,2866.83,Monthly,UPI,NaN,N,2024-12-20
158,NaN,NaN,39,11.0,113.87,511.26,One year,Credit Card,DSL,NaN,2023-11-24
174,NaN,Male,69,12.0,92.40,1707.09,Two year,UPI,Fiber optic,Y,29/08/2022
202,NaN,M,22,1.0,116.60,2651.20,Monthly,Credit Card,Fiber optic,Y,24/11/2020
...,...,...,...,...,...,...,...,...,...,...,...
101957,NaN,Female,23,2.0,28.12,677.91,month-to-month,Debit Card,Fiber optic,Yes,2020-03-16
101962,NaN,NaN,30,26.0,92.06,9289.88,month-to-month,UPI,NaN,N,2023-02-23
101979,NaN,NaN,18,39.0,110.40,3447.71,One year,Net Banking,NaN,Y,09-20-2021
101986,NaN,F,69,35.0,99.24,4270.87,One year,Net Banking,DSL,Yes,2021/11/05
101992,NaN,NaN,unknown,17.0,126.67,3574.61,Monthly,Net Banking,NaN,Yes,2021/01/02

In [10]:
df['gender'].unique()

<StringArray>
['F', 'Female', 'M', nan, 'Male']
Length: 5, dtype: str

In [11]:
df['contract_type'].unique()

<StringArray>
[nan, 'Monthly', 'One year', 'Two year', 'month-to-month']
Length: 5, dtype: str

In [12]:
df['payment_method'].unique()

<StringArray>
['Debit Card', 'Net Banking', 'UPI', nan, 'Credit Card']
Length: 5, dtype: str

In [13]:
df['internet_service'].unique()

<StringArray>
[nan, 'Fiber optic', 'DSL']
Length: 3, dtype: str

In [14]:
df['churn'].value_counts()

churn
No     25135
Yes    25125
Y      24813
N      24809
Name: count, dtype: int64

In [15]:
df['churn'].unique()

<StringArray>
['No', 'N', 'Y', nan, 'Yes']
Length: 5, dtype: str

In [16]:
df[pd.to_numeric(df['age'], errors='coerce') > 90]

Empty DataFrame
Columns: [customer_id, gender, age, tenure, monthly_charges, total_charges, contract_type, payment_method, internet_service, churn, signup_date]
Index: []

In [17]:
df['age'].unique()

<StringArray>
[     '52',      '63',      '68',      '60',      '24',      '43',      '55',
      '27',      '58',      '62',      '53',      '33',      '54',      '23',
      '41',      '59',      '35',      '29',      '64',      '40', 'unknown',
      '67',      '61',       nan,      '36',      '42',      '45',      '44',
      '20',      '56',      '21',      '22',      '34',      '25',      '66',
      '26',      '65',      '69',      '30',      '49',      '32',      '51',
      '19',      '28',      '57',      '38',      '47',      '46',      '50',
      '48',      '31',      '37',      '39',      '18']
Length: 54, dtype: str

In [18]:
df['churn'].isnull().sum()

np.int64(2118)

In [19]:
df['customer_id'].isnull().sum()

np.int64(2115)

In [20]:
df['customer_id'].duplicated().sum()

np.int64(42304)

In [21]:
df.duplicated().sum()

np.int64(2000)

In [22]:
df['signup_date'].isnull().sum()

np.int64(2121)

In [23]:
df[df['churn']='true']

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (495630863.py, line 1)